HAI
    OBTW
    I HAS A a ITZ SUM OF 2 AN 4
    I HAS A b ITZ DIFF OF 4 AN 3.14
    I HAS A c ITZ PRODUKT OF "2" AN "7"
    I HAS A d ITZ QUOSHUNT OF 5 AN "12"
    I HAS A e ITZ MOD OF 3 AN "3.14"
    I HAS A f ITZ SUM OF QUOSHUNT OF PRODUKT OF 3 AN 4 AN 2 AN 1
    TLDR
    I HAS A g ITZ SUM OF SUM OF SUM OF 3 AN 4 AN 2 AN 1   
KTHXBYE