HAI
    a R BOTH OF WIN AN FAIL
    b R EITHER OF FAIL AN WIN
    c R WON OF WIN AN WIN
    d R NOT FAIL
    e R ALL OF NOT WIN AN BOTH OF WIN AN FAIL AN EITHER OF FAIL AN FAIL MKAY 

    VISIBLE a 
    VISIBLE b 
    VISIBLE c 
    VISIBLE d 
    VISIBLE e 

KTHXBYE